name: Deploy
on:
  push:
    branches:
      - dev

jobs:
  test:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Copy env for test
        run: cp .env.test .env

      - name: Install node dependencies
        run: npm ci && npm --prefix functions ci

      - name: Run prepare
        run: npm run prepare

      - name: Run type-check
        run: npm run check

      - name: Run linter
        run: npm run lint

      - name: Run build test
        run: npm run build

#      - name: Install Playwright
#        run: npx playwright install --with-deps
#
#      - name: Run test
#        run: npm run test

  deploy:
    name: Deploy
    needs:
      - test
    runs-on: ubuntu-latest

    environment: Production
    env:
      FIREBASE_CLI_EXPERIMENTS: pintags
      SVELTE_APP_NAME: ${{ vars.SVELTE_APP_NAME }}
      MAIL_FROM_NAME: ${{ vars.MAIL_FROM_NAME }}
      MAIL_FROM_ADDRESS: ${{ vars.MAIL_FROM_ADDRESS }}
      ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
      STORAGE_API: ${{ secrets.STORAGE_API }}
      STORAGE_BUCKET: ${{ vars.STORAGE_BUCKET }}

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install node dependencies
        run: npm ci

      - name: Run prepare
        run: npm run prepare

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}

      - name: Authenticate to Firebase
        uses: w9jds/setup-firebase@main
        with:
          firebase_token: ${{ secrets.FIREBASE_TOKEN }}

      - name: Deploy to Firebase
        run: npm run firebase:deploy
