name: Deploy
on:
  push:
    branches:
      - dev

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout branch

      - uses: actions/setup-node@v3
        name: Setup Node
        with:
          node-version: 18
          cache: 'npm'

      - name: Copy env for test
        run: cp .env.test .env

      - name: Install node dependencies
        run: npm ci && npm --prefix functions ci

      - name: Run prepare
        run: npm run prepare

      - name: Run type-check
        run: npm run check

      - name: Run linter
        run: npm run lint

      - name: Run build test
        run: npm run bundle

#      - name: Install Playwright
#        run: npx playwright install --with-deps
#
#      - name: Run test
#        run: npm run test

  deploy:
    name: Deploy
    needs:
      - test
    runs-on: ubuntu-latest

    environment: prod
    env:
      SVELTE_APP_NAME: ${{ vars.SVELTE_APP_NAME }}
      ORIGIN: ${{ vars.ORIGIN }}
      MAIL_FROM_NAME: ${{ secrets.MAIL_FROM_NAME }}
      MAIL_FROM_ADDRESS: ${{ secrets.MAIL_FROM_ADDRESS }}
      ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
      GOOGLE_CLOUD_PROJECT: ${{ secrets.GOOGLE_CLOUD_PROJECT }}
      STORAGE_API: ${{ secrets.STORAGE_API }}
      STORAGE_BUCKET: ${{ secrets.STORAGE_BUCKET }}

    steps:
      - uses: actions/checkout@v3
        name: Checkout branch

      - uses: actions/setup-node@v3
        name: Setup Node
        with:
          node-version: 18
          cache: 'npm'

      - name: Install node dependencies
        run: npm ci

      - name: Run prepare
        run: npm run prepare

      - name: Run build
        run: npm run bundle

      - name: Set Google credentials
        run: cp ${{ secrets.GOOGLE_CREDENTIALS }} > ${{ github.workspace }}/${{ vars.GOOGLE_CREDENTIALS_PATH }}

      - name: Deploy to Firebase
        uses: joinflux/firebase-tools@master
        with:
          args: deploy --only functions,hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ vars.GOOGLE_CREDENTIALS_PATH }}
