name: Deploy
on:
  push:
    branches:
      - dev

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout branch

      - uses: actions/setup-node@v3
        name: Setup Node
        with:
          node-version: 18
          cache: 'npm'

      - name: Copy env for test
        run: cp .env.test .env

      - name: Install node dependencies
        run: npm ci && npm --prefix functions ci

      - name: Run type-check
        run: npm run check

      - name: Run linter
        run: npm run lint

      - name: Run build test
        run: npm run build

      - name: Run functions build test
        run: npm --prefix functions run build

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run test
        run: npm run test

  deploy:
    name: Deploy
    needs:
      - test
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v3
        name: Checkout branch

      - uses: actions/setup-node@v3
        name: Setup Node
        with:
          node-version: 18
          cache: 'npm'

      - name: Install node dependencies
        run: npm ci

      - name: Run build
        run: npm run build

      - name: Deploy to Firebase
        uses: joinflux/firebase-tools@master
        with:
          args: deploy --only functions,hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
