name: CI
on: pull_request

jobs:
  test:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Copy env for test
        run: cp .env.test .env

      - name: Install node dependencies
        run: npm install

      - name: Run prepare
        run: npm run prepare

      - name: Run type-check
        run: npm run check

      - name: Run linter
        run: npm run lint

      - name: Run build test
        run: npm run build

#      - name: Install Playwright
#        run: npx playwright install --with-deps
#
#      - name: Run test
#        run: npm run test

  deploy:
    name: Deploy
    needs:
      - test
    runs-on: ubuntu-latest

    environment: Preview
    env:
      PUBLIC_APP_ENV: "preview"
      PUBLIC_APP_NAME: ${{ vars.PUBLIC_APP_NAME }}
      MAIL_FROM_NAME: ${{ vars.MAIL_FROM_NAME }}
      MAIL_FROM_ADDRESS: ${{ vars.MAIL_FROM_ADDRESS }}
      ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
      STORAGE_API: ${{ vars.STORAGE_API }}
      STORAGE_BUCKET: ${{ vars.STORAGE_BUCKET }}

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install node dependencies
        run: npm install

      - name: Run prepare
        run: npm run prepare

      - name: Run build
        run: npm run build

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}

      - name: Deploy to Firebase Functions
        run: npm run firebase:deploy:functions

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        env:
          FIREBASE_CLI_EXPERIMENTS: pintags
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channelId: ${{ vars.GITHUB_REF_NAME }}
