name: CI
on: pull_request

jobs:
  test:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Copy env for test
        run: cp .env.test .env

      - name: Install node dependencies
        run: npm install

      - name: Run prepare
        run: npm run prepare

      - name: Run type-check
        run: npm run check

      - name: Run linter
        run: npm run lint

      - name: Run build
        run: npm run build

      - name: Setup test .env
        run: cp .env.test .env

#      - name: Install Playwright Browsers
#        run: npx playwright install --with-deps

      - name: Setup Firebase
        uses: w9jds/setup-firebase@main
        with:
          tools-version: latest
          firebase_token: ${{ secrets.FIREBASE_TOKEN }}

      - name: Setup Firebase Extensions
        run: firebase ext:export --force

      - name: Replace SMTP URI for Extensions
        uses: Langsdorf/env-replace@v1.0.0
        with:
          key: "SMTP_CONNECTION_URI"
          value: ${{ vars.MAILTRAP_URI }}
          file: "./extensions/firestore-send-email.env"

      - name: Replace SMTP Password for Extensions
        uses: Langsdorf/env-replace@v1.0.0
        with:
          key: "SMTP_PASSWORD"
          value: ${{ secrets.MAILTRAP_PASSWORD }}
          file: "./extensions/firestore-send-email.env"

#      - name: Run test
#        uses: w9jds/firebase-action@master
#        with:
#          args: emulators:exec --only=auth,firestore,storage,extensions 'sudo ./runner/test.sh'
#          cache: 'firebase-emulators'
#        env:
#          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
#          FIREBASE_CLI_EXPERIMENTS: webframeworks,pintags

      - name: Run test
        run: sudo npm run firebase:emu:test
        with:
          cache: 'firebase-emulators'
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_CLI_EXPERIMENTS: webframeworks,pintags

      - name: Cache emulators
        uses: actions/cache@v3
        with:
          key: firebase-emulators
          path: /github/home/.cache/firebase/emulators

  deploy:
    name: Deploy
    needs:
      - test
    runs-on: ubuntu-latest

    environment: Preview

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install node dependencies
        run: npm ci

      - name: Run prepare
        run: npm run prepare

      - name: Make .env file for dynamic env
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_PUBLIC_SENTRY_DSN: ${{ vars.SENTRY_DSN }}
          envkey_PUBLIC_SENTRY_SAMPLE_RATE: ${{ vars.SENTRY_SAMPLE_RATE }}
          file_name: .env

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        env:
          NODE_ENV: production
          ORIGIN: ${{ vars.ORIGIN }}
          PUBLIC_APP_ENV: preview
          PUBLIC_APP_NAME: ${{ vars.PUBLIC_APP_NAME }}
          STORAGE_API: ${{ vars.STORAGE_API }}
          STORAGE_BUCKET: ${{ vars.STORAGE_BUCKET }}
          MAIL_FROM_NAME: ${{ vars.MAIL_FROM_NAME }}
          MAIL_FROM_ADDRESS: ${{ vars.MAIL_FROM_ADDRESS }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          FIREBASE_CLI_EXPERIMENTS: webframeworks,pintags
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channelId: ${{ vars.GITHUB_REF_NAME }}

