name: CI
on: pull_request

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Copy env for test
        run: cp .env.test .env

      - name: Install node dependencies
        run: npm ci && npm --prefix functions ci

      - name: Run prepare
        run: npm run prepare

      - name: Run type-check
        run: npm run check

      - name: Run linter
        run: npm run lint

      - name: Run build test
        run: npm run build

#      - name: Install Playwright
#        run: npx playwright install --with-deps
#
#      - name: Run test
#        run: npm run test
